feign:
  client:
    config:
      default:
        readTimeout: 1500
        connectTimeout: 500


currency-service:
  base:
    url: https://openexchangerates.org/api/
  name: feignCurrencyService

gif-service:
  base:
    url: https://api.giphy.com/v1/gifs
  name: feignGifService



